### ISSUE TITLE
Test failures and no tracing directory

### ISSUE THREAD

**Issue by alsora** [ros-realtime/reference-system#40] opened 2021-10-06 12:18 UTC
Hi, I just built and run tests using a ROS 2 Galactic Docker container on my laptop.
There are several test failures in the `autoware_reference_system` package and no `tracing` directory is generated.

```
The following tests FAILED:
	  3 - test_requirements_autoware_default_multithreaded.py (Timeout)
	  4 - generate_traces_autoware_default_singlethreaded_rmw_cyclonedds_cpp_5s.py (Failed)
	  7 - generate_traces_autoware_default_singlethreaded_rmw_fastrtps_cpp_5s.py (Failed)
	 10 - generate_traces_autoware_default_staticsinglethreaded_rmw_cyclonedds_cpp_5s.py (Failed)
	 13 - generate_traces_autoware_default_staticsinglethreaded_rmw_fastrtps_cpp_5s.py (Failed)
	 16 - generate_traces_autoware_default_multithreaded_rmw_cyclonedds_cpp_5s.py (Failed)
	 19 - generate_traces_autoware_default_multithreaded_rmw_fastrtps_cpp_5s.py (Failed)
```

The timeout test output is the following
```
test 3
      Start  3: test_requirements_autoware_default_multithreaded.py

3: Test command: /usr/bin/python3 "-u" "/opt/ros/galactic/share/ament_cmake_test/cmake/run_test.py" "/root/ws/build/autoware_reference_system/test_results/autoware_reference_system/test_requirements_autoware_default_multithreaded.py.xunit.xml" "--package-name" "autoware_reference_system" "--output-file" "/root/ws/build/autoware_reference_system/ros_test/test_requirements_autoware_default_multithreaded.py.txt" "--command" "ros2" "test" "/root/ws/build/autoware_reference_system/test_requirements_autoware_default_multithreaded.py" "--junit-xml=/root/ws/build/autoware_reference_system/test_results/autoware_reference_system/test_requirements_autoware_default_multithreaded.py.xunit.xml" "--package-name=autoware_reference_system"
3: Test timeout computed to be: 3
3: -- run_test.py: invoking following command in '/root/ws/build/autoware_reference_system':
3:  - ros2 test /root/ws/build/autoware_reference_system/test_requirements_autoware_default_multithreaded.py --junit-xml=/root/ws/build/autoware_reference_system/test_results/autoware_reference_system/test_requirements_autoware_default_multithreaded.py.xunit.xml --package-name=autoware_reference_system
3: Running with ROS_DOMAIN_ID 1
3: ROS_DOMAIN_ID 1
3: [INFO] [launch]: All log files can be found below /root/.ros/log/2021-10-06-12-10-13-825881-elysium-24603
3: [INFO] [launch]: Default logging verbosity is set to INFO
3: test_pubs_and_subs (autoware_reference_system.TestRequirementsAutowareReferenceSystem) ... 1633522213.832365 [1]       ros2: using network interface wlp0s20f3 (udp/192.168.0.130) selected arbitrarily from: wlp0s20f3, enx381428ab9836, docker0, cscotun0
3: [INFO] [test_requirements_autoware_default_multithreaded-1]: process started with pid [24608]
3: [test_requirements_autoware_default_multithreaded-1] 1633522213.837433 [1] autoware_d: using network interface wlp0s20f3 (udp/192.168.0.130) selected arbitrarily from: wlp0s20f3, enx381428ab9836, docker0, cscotun0
3: [test_requirements_autoware_default_multithreaded-1] [INFO] [rclcpp]: Currently used middleware can't loan messages. Local allocator will be used.
3: topic_monitor looping:
3: Topic monitor data collected
3: 		/FrontLidarDriver: ['topic_exists'=True, 'pubs_match'=True, 'subs_match'=True]
3: 		/RearLidarDriver: ['topic_exists'=True, 'pubs_match'=True, 'subs_match'=True]
3: 		/PointCloudMap: ['topic_exists'=True, 'pubs_match'=True, 'subs_match'=True]
3: 		/Visualizer: ['topic_exists'=True, 'pubs_match'=True, 'subs_match'=True]
3: 		/Lanelet2Map: ['topic_exists'=True, 'pubs_match'=True, 'subs_match'=True]
3: 		/PointsTransformerFront: ['topic_exists'=True, 'pubs_match'=True, 'subs_match'=True]
3: 		/PointsTransformerRear: ['topic_exists'=True, 'pubs_match'=True, 'subs_match'=True]
3: 		/VoxelGridDownsampler: ['topic_exists'=True, 'pubs_match'=True, 'subs_match'=True]
3: 		/PointCloudMapLoader: ['topic_exists'=True, 'pubs_match'=True, 'subs_match'=True]
3: 		/EuclideanClusterDetector: ['topic_exists'=True, 'pubs_match'=True, 'subs_match'=True]
3: 		/ObjectCollisionEstimator: ['topic_exists'=True, 'pubs_match'=True, 'subs_match'=True]
3: 		/MPCController: ['topic_exists'=True, 'pubs_match'=True, 'subs_match'=True]
3: 		/ParkingPlanner: ['topic_exists'=True, 'pubs_match'=True, 'subs_match'=True]
3: 		/LanePlanner: ['topic_exists'=True, 'pubs_match'=True, 'subs_match'=True]
3: 		/PointCloudFusion: ['topic_exists'=True, 'pubs_match'=True, 'subs_match'=True]
3: 		/NDTLocalizer: ['topic_exists'=True, 'pubs_match'=True, 'subs_match'=True]
3: 		/VehicleInterface: ['topic_exists'=True, 'pubs_match'=True, 'subs_match'=True]
3: 		/Lanelet2GlobalPlanner: ['topic_exists'=True, 'pubs_match'=True, 'subs_match'=True]
3: 		/Lanelet2MapLoader: ['topic_exists'=True, 'pubs_match'=True, 'subs_match'=True]
3: 		/BehaviorPlanner: ['topic_exists'=True, 'pubs_match'=True, 'subs_match'=True]
3: [INFO] [test_requirements_autoware_default_multithreaded-1]: sending signal 'SIGINT' to process[test_requirements_autoware_default_multithreaded-1]
3: [test_requirements_autoware_default_multithreaded-1] [INFO] [rclcpp]: signal_handler(signal_value=2)
 3/29 Test  #3: test_requirements_autoware_default_multithreaded.py ..............................***Timeout   3.00 sec
```

The failures look all like this
```
test 19
      Start 19: generate_traces_autoware_default_multithreaded_rmw_fastrtps_cpp_5s.py

19: Test command: /usr/bin/python3 "-u" "/opt/ros/galactic/share/ament_cmake_test/cmake/run_test.py" "/root/ws/build/autoware_reference_system/test_results/autoware_reference_system/generate_traces_autoware_default_multithreaded_rmw_fastrtps_cpp_5s.py.xunit.xml" "--package-name" "autoware_reference_system" "--output-file" "/root/ws/build/autoware_reference_system/ros_test/generate_traces_autoware_default_multithreaded_rmw_fastrtps_cpp_5s.py.txt" "--command" "ros2" "test" "/root/ws/build/autoware_reference_system/generate_traces_autoware_default_multithreaded_rmw_fastrtps_cpp_5s.py" "--junit-xml=/root/ws/build/autoware_reference_system/test_results/autoware_reference_system/generate_traces_autoware_default_multithreaded_rmw_fastrtps_cpp_5s.py.xunit.xml" "--package-name=autoware_reference_system"
19: Test timeout computed to be: 10
19: -- run_test.py: invoking following command in '/root/ws/build/autoware_reference_system':
19:  - ros2 test /root/ws/build/autoware_reference_system/generate_traces_autoware_default_multithreaded_rmw_fastrtps_cpp_5s.py --junit-xml=/root/ws/build/autoware_reference_system/test_results/autoware_reference_system/generate_traces_autoware_default_multithreaded_rmw_fastrtps_cpp_5s.py.xunit.xml --package-name=autoware_reference_system
19: Running with ROS_DOMAIN_ID 1
19: ROS_DOMAIN_ID 1
19: [INFO] [launch]: All log files can be found below /root/.ros/log/2021-10-06-12-10-24-919767-elysium-24699
19: [INFO] [launch]: Default logging verbosity is set to INFO
19: Task exception was never retrieved
19: future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py:226> exception=RuntimeError('channel enabling failed: Kernel tracer not available')>
19: Traceback (most recent call last):
19:   File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
19:     await self.__process_event(next_event)
19:   File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
19:     visit_all_entities_and_collect_futures(entity, self.__context))
19:   File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
19:     futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
19:   File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
19:     futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
19:   File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
19:     futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
19:   [Previous line repeated 1 more time]
19:   File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
19:     sub_entities = entity.visit(context)
19:   File "/opt/ros/galactic/lib/python3.8/site-packages/launch/action.py", line 108, in visit
19:     return self.execute(context)
19:   File "/root/ws/install/tracetools_launch/lib/python3.8/site-packages/tracetools_launch/action.py", line 127, in execute
19:     self._setup()
19:   File "/root/ws/install/tracetools_launch/lib/python3.8/site-packages/tracetools_launch/action.py", line 131, in _setup
19:     trace_directory = lttng.lttng_init(
19:   File "/root/ws/install/tracetools_trace/lib/python3.8/site-packages/tracetools_trace/tools/lttng.py", line 52, in lttng_init
19:     trace_directory = _lttng.setup(**kwargs)
19:   File "/root/ws/install/tracetools_trace/lib/python3.8/site-packages/tracetools_trace/tools/lttng_impl.py", line 151, in setup
19:     _enable_channel(handle_kernel, channel_kernel)
19:   File "/root/ws/install/tracetools_trace/lib/python3.8/site-packages/tracetools_trace/tools/lttng_impl.py", line 280, in _enable_channel
19:     raise RuntimeError(f'channel enabling failed: {lttng.strerror(result)}')
19: RuntimeError: channel enabling failed: Kernel tracer not available
19: Task exception was never retrieved
19: future: <Task finished name='Task-3' coro=<LaunchService._process_one_event() done, defined at /opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py:226> exception=RuntimeError('failed to stop tracing: Tracing has already been stopped')>
19: Traceback (most recent call last):
19:   File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
19:     await self.__process_event(next_event)
19:   File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py", line 237, in __process_event
19:     entities = event_handler.handle(event, self.__context)
19:   File "/opt/ros/galactic/lib/python3.8/site-packages/launch/event_handlers/on_shutdown.py", line 58, in handle
19:     return self.__on_shutdown(cast(Shutdown, event), context)
19:   File "/root/ws/install/tracetools_launch/lib/python3.8/site-packages/tracetools_launch/action.py", line 142, in _destroy
19:     lttng.lttng_fini(session_name=self.__session_name)
19:   File "/root/ws/install/tracetools_trace/lib/python3.8/site-packages/tracetools_trace/tools/lttng.py", line 63, in lttng_fini
19:     _lttng.stop(**kwargs)
19:   File "/root/ws/install/tracetools_trace/lib/python3.8/site-packages/tracetools_trace/tools/lttng_impl.py", line 192, in stop
19:     raise RuntimeError(f'failed to stop tracing: {lttng.strerror(result)}')
19: RuntimeError: failed to stop tracing: Tracing has already been stopped
19: Processes under test stopped before tests completed
19: -- run_test.py: return code 1
19: -- run_test.py: verify result file '/root/ws/build/autoware_reference_system/test_results/autoware_reference_system/generate_traces_autoware_default_multithreaded_rmw_fastrtps_cpp_5s.py.xunit.xml'
19/29 Test #19: generate_traces_autoware_default_multithreaded_rmw_fastrtps_cpp_5s.py ............***Failed    0.43 sec
```

**Comment by flynneva** [comment] 2021-10-06 12:57
@alsora from the errors it looks like you do not have LTTng enabled for your environment. Did you follow the steps to install 'ros2_tracing'

I was thinking of adding a cmake arg to run tests without LTTng since with #33 we run cpu and memory tests using psrecord.

I'd recommend trying out #33's branch as it should have updated READMEs as well.

**Comment by alsora** [comment] 2021-10-06 14:03
I updated my branch now that you merged #33.

Now the test is running since 36 minutes. Is this expected?
P.S. I had to make a couple of changes wrt the instructions:
```
pip install -U psrecord
touch src/ros2_tracing/test_tracetools/COLCON_IGNORE
```

I think that the colcon ignore is needed because the ros2_tracking package is supposed to be used with master and not galactic

**Comment by flynneva** [comment] 2021-10-06 14:21
@alsora ive always checked out the ros2_tracing branch for my specific district (so for Galactic check out the galactic branch).  That's what has worked for me.

36min sounds like too long. What does the log file look like for the test?

**Comment by flynneva** [comment] 2021-10-06 17:13
@alsora LTTng tracing generates lots of data and can be quite slow. I haven't tried it in a docker container yet but I'd imagine that it might be even slower than what I'm seeing....

the log files do get quite large as its logging all the stdouts from each test run. I've only seen it hang once before and that was due [to a bug in the timing settings for the multithreaded executor](https://github.com/ros-realtime/reference-system/commit/71a192f885d5b91ac6b955eb9e891251b768e7b0#diff-b54127a03ffdc2a0acb93e35dabaeec4f1a01707880bebf7d9451f3168bc33b2L27). the output you show above looks similar but should not be a problem in the current `main` branch

**Comment by flynneva** [comment] 2021-10-06 17:15
> Test timeout computed to be: 10000000

@alsora I should adjust the timeout though so it does end cleanly on its own 😅

**Comment by alsora** [comment] 2021-10-06 17:26
My computer is a 16 cores i9 processor of last year.
I'm afraid of how much time it would take on a raspberry pi if this is expected behavior.

**Comment by flynneva** [comment] 2021-10-06 17:36
@alsora it is not the expected behavior to run indefinitely. something is wrong.

could you share with me your build logs and test log files?

**Comment by flynneva** [comment] 2021-10-06 18:03
@alsora thanks for sending those over. looking through the test logs it looks like there are a few problems.

the first is something appears to be wrong with your `ros2_tracing` LTTng setup:

```
[5.240s] 4: RuntimeError: channel enabling failed: Kernel tracer not available
....
[5.241s] 4: RuntimeError: failed to stop tracing: Tracing has already been stopped
[5.241s] 4: Processes under test stopped before tests completed
```

after building, did you source the newly built `ros2_tracing` binaries running `source install/setup.bash` before running colcon test? I'm not really a `ros2_tracing` expert though so not sure if thats the problem.

the step thats failing is the `generate_memory_trace` step which uses `psrecord` to generate some cpu and memory usage data while running a process.  it looks like whatever version of `psrecord` you have doesnt accept the `Duration` argument like the `psrecord` program I have installed.

how did you install `psrecord`?

what happens when you run this command in a terminal?

```
RMW_IMPLEMENTATION=rmw_cyclonedds_cpp               /root/ws/install/autoware_reference_system/share/autoware_reference_system/scripts/benchmark_one.sh               $(ros2 pkg prefix autoware_reference_system)/lib/autoware_reference_system/autoware_default_singlethreaded               5               /root/.ros/memory               autoware_default_singlethreaded_rmw_cyclonedds_cpp_5s.txt
```

**Comment by christophebedard** [comment] 2021-10-06 18:08
> [5.240s] 4: RuntimeError: channel enabling failed: Kernel tracer not available
> ....
> [5.241s] 4: RuntimeError: failed to stop tracing: Tracing has already been stopped
> [5.241s] 4: Processes under test stopped before tests completed

This is because you haven't installed the LTTng kernel tracer, or perhaps because your non-root user isn't in the `tracing` group

However, kernel tracing is *currently* not needed. #44 will remove the need for the kernel tracer. We might re-add it later on though.

**Comment by alsora** [comment] 2021-10-07 11:50
Thank you for the information.
I added the default docker user to the tracing group (why does the user need to be non-root?)

Anyhow I have the following:
 - If `psrecord` is installed --> test 8 stalls forever. 
 - If `psrecord` is not installed --> all test complete (with failures and nothing gets generated).

In the logs I had
```

**Comment by razr** [comment] 2021-10-10 23:08
@flynneva @christophebedard I run it on my RPI4 and have similar problems:

```bash
ubuntu@ubuntu:~/ros2$ uname -a
Linux ubuntu 5.4.0-1044-raspi #48-Ubuntu SMP PREEMPT Thu Sep 9 15:24:01 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

ubuntu@ubuntu:~/ros2$ echo $ROS_DISTRO
galactic

ubuntu@ubuntu:~/ros2/src/ros2_tracing$ git branch
* galactic

ubuntu@ubuntu:~/ros2/src/reference-system$ git branch
* main

ubuntu@ubuntu:~/ros2$ ros2 trace
UST tracing enabled (19 events)
kernel tracing enabled (4 events)
context (3 names)
writing tracing session to: /home/ubuntu/.ros/tracing/session-20211011005442
press enter to start...
press enter to stop...
```

then I start ```colcon test```
```bash
ubuntu@ubuntu:~/ros2$ colcon test --packages-select $(colcon list -n --base-paths src/reference-system/)
...
[Processing: autoware_reference_system]
--- stderr: autoware_reference_system
Errors while running CTest
---
Finished <<< autoware_reference_system [4min 7s]        [ with test failures ]
0;colcon test [3/3 done] [0 ongoing]
```
and it fails after a while and no tracing dir is generated

**Comment by flynneva** [comment] 2021-10-16 01:33
@alsora please try the new `0.1.1` release with the cmake argument `-DSKIP_TRACING`. this should disable the `ros2_tracing` tests from being run and you should now find reports generated in the `~/.ros/memory` and your `workspace/log/latest_test/autoware_reference_system` directories.

closing this now as I think it has been addressed

**Closed by flynneva** 2021-10-16 01:33 UTC
